require("modules.LongAssembler.data")
require("modules.SmallAssembler.data")
require("modules.OreVariety.data")
require("modules.PermanentMachines.data")
require("modules.HotterSteamResearch.data")
require("modules.LongerInserters.data")